{% set name = "ocsmesh" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/74/20/8652e8fee5fb7df63a9650c34c679039211c8e6f9c15b1fd8ed39ac65d9a/ocsmesh-{{ version }}.tar.gz
  sha256: 3173f3f31f43c675bf708d53bfc7bc5a3b45208f81581b93eff399ddb2c0e64f

build:
  entry_points:
    - ocsmesh = ocsmesh.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=7
    - wheel
    - numpy
    - pip
  run:
    - python >={{ python_min }}
    - colored-traceback
    - fiona
    - geopandas >=1.0.0
    - jigsawpy
    - matplotlib-base
    - netcdf4
    - numba
    - numpy >=1.21
    - pyarrow
    - rtree
    - pyproj >=3.0
    - rasterio
    - scipy
    - shapely
    - typing-extensions
    - utm
    - pandas
    - py-triangle

test:
  imports:
    - ocsmesh
  commands:
    - pip check
    - ocsmesh --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/noaa-ocs-modeling/OCSMesh/
  summary: Package to generate computational unstructured meshes from planetary modeling.
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felicio93
    - saeed-moghimi-noaa
    - SorooshMani-NOAA
