{% set name = "ocsmesh" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/01/d3/515e31b5fe2b9409ce301b6bf14bf437438faefb57666bede18ff364be3a/ocsmesh-{{ version }}.tar.gz
  sha256: 5fffc9c41fff83d6c458c90a057ba4a83860537411c978e9cfdbebd92fd2cacb

build:
  entry_points:
    - ocsmesh = ocsmesh.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=7
    - wheel
    - numpy
    - pip
  run:
    - python >={{ python_min }}
    - colored-traceback
    - fiona
    - geopandas >=1.0.0
    - jigsawpy
    - matplotlib-base
    - netcdf4
    - numba
    - numpy >=1.21
    - pyarrow
    - rtree
    - pyproj >=3.0
    - rasterio
    - scipy
    - shapely
    - typing-extensions
    - utm
    - pandas
    - py-triangle

test:
  imports:
    - ocsmesh
  commands:
    - pip check
    - ocsmesh --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/noaa-ocs-modeling/OCSMesh/
  summary: Package to generate computational unstructured meshes from planetary modeling.
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felicio93
    - saeed-moghimi-noaa
    - SorooshMani-NOAA
