{% set name = "ocsmesh" %}
{% set version = "1.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ocsmesh-{{ version }}.tar.gz
  sha256: 6c300d67d7be3463f101b6e3a51c3e81a6fc5480221769c37cb3517e438387f9

build:
  entry_points:
    - ocsmesh = ocsmesh.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=7
    - wheel
    - numpy
    - pip
  run:
    - python >=3.9
    - colored-traceback
    - fiona
    - geopandas<=0.14.4
    - jigsawpy
    - matplotlib-base
    - netcdf4
    - numba
    - numpy >=1.21
    - pyarrow
    - rtree
    - pyproj >=3.0
    - rasterio
    - scipy
    - shapely
    - typing-extensions
    - utm
    - pandas
    - py-triangle

test:
  imports:
    - ocsmesh
  commands:
    - pip check
    - ocsmesh --help
  requires:
    - pip

about:
  home: https://github.com/noaa-ocs-modeling/OCSMesh/
  summary: Package to generate computational unstructured meshes from planetary modeling.
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felicio93
    - saeed-moghimi-noaa
    - SorooshMani-NOAA
